@startuml
' Verteilungssicht: UML-konformes Deployment-Diagramm

frame "Verteilungssicht" {

    node "PC/Rechner" as pc {
        artifact "UI"
    }

    node "ITS-BRD" as brd {
        artifact "IO"
    }

    node "Raspberry Pi" as pi {
        artifact "ActuatorController"
    }

    node "Cloud" as cloud {
        artifact "StateService"
        artifact "MoveAdapter"
        artifact "Controller"
    }
}

' Kommunikationsbeziehungen
brd --> cloud 
pi <--> cloud 
cloud --> pc 
@enduml