@startuml
actor User

participant "IO/UI" as UI
participant "LCD-Controller" as Ctrl
participant "Modell" as Modell


' Benutzer wählt einen Roboter (z. B. über Button)
User -> UI: Auswahl "R1" treffen

' UI Button bestätigen
UI -> Ctrl: onButtonSelect("R1")


' LCD-Controller nutzt Roboterauswahl
Ctrl -> Modell: roboterAuswahl("R1")
@enduml