@startuml
actor Applikation
participant Watchdog
participant "Name Service" as NS

== Registrierung ==
Applikation -> Watchdog : Register(name)
Watchdog -> NS : Resolve(name)
NS --> Watchdog : IP/Port

== Initiale Knotenliste==
'Hieer würde der Watchdog die liste von der Middleware bekommen
Watchdog -> Watchdog : Vergleiche neue liste der Middleware mit eigener liste
Watchdog -> Applikation : SendAvailableNodesList()

== Überwachungsphase ==
loop Regelmäßige Heartbeats
    Applikation -> Watchdog : Heartbeat(name) von allen Nodes


== Ausfallerkennung ==
alt Heartbeat nicht empfangen (Timeout)
    Watchdog -> Applikation : NotifyFailure(name)
    Applikation -> Applikation : Teilnehmer deaktivieren
end
end
@enduml